### ISSUE TITLE
Not able to register customer.

### ISSUE THREAD

**Issue by jyoti-webkul** [aayushbhatt18/laravel-pwa#1]
- Bagisto version: 1.1.1

----------------------------------------------------

![Workspace 1_056](https://user-images.githubusercontent.com/45203177/80389421-b03f5a00-88c8-11ea-8925-204fd1b9e833.png)

**Comment by aayushbhatt18** [comment]
Fixed.

**Comment by jyoti-webkul** [comment]
- Framework Version: 1.1.1
- Pwa: branch-aayush

---------------------------------------------

Fixed

![Workspace 1_068](https://user-images.githubusercontent.com/45203177/80809290-fbb27a80-8bde-11ea-81b1-2bca39608b3a.png)
